### ISSUE TITLE
Current db is old?

### ISSUE THREAD

**Issue by ammaraziz** [ojcharles/herpesdrg#18]
Hey,

I noticed that `herpesdrg` is pointing towards this: https://github.com/ojcharles/herpesdrg-db/tree/cfcb051d5ee2a4096ba374562157acacc513fc06 which is ~2 years old. 

Should I switch over to the new version of the db?

**Comment by ojcharles** [comment]
oh excellent spot! Thanks Ammar, let me make a hotfix now.
